# Generated by Django 2.1.7 on 2019-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_city', models.CharField(max_length=25)),
                ('emp_address', models.CharField(max_length=250)),
                ('emp_created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newuser',
            },
        ),
    ]
