# Generated by Django 2.1.7 on 2019-10-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='emp_addres',
            new_name='emp_address',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='emp_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
