# Generated by Django 2.1.7 on 2019-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_city', models.CharField(max_length=25)),
                ('user_number', models.CharField(max_length=10)),
            ],
        ),
    ]
