# Generated by Django 2.1.7 on 2019-10-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_picture',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
